### ISSUE TITLE
[feature] Display created/modified at/by fields.

### ISSUE THREAD

**Issue by derekdreery** [Intermesh/groupoffice#200] opened 2018-09-04 11:07 UTC
In 6.2 these fields are displayed, in 6.3 they are not.

I know that this issue has already been raised, I'm putting it here for completeness. :)

**Comment by mschering** [comment] 2018-09-11 08:38
Duplicate of Ctime mtime cuser and muser not displayed in address book #169

**Closed** 2018-09-11 08:39 UTC
