### ISSUE TITLE
6.4.24 - Calendar - Error when accepting invite from other GO user

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#424] opened 2019-06-28 09:46 UTC
When accepting an invite from an other GO user by clicking on "Indicate whether you participate in this event" we get:
The participant of this event is missing

![Go-InviteError](https://user-images.githubusercontent.com/52159663/60333506-25808c80-9991-11e9-804d-1cff9c53d0de.png)

Also I noticed that the invite from the other GO user arrives with two ics file attached: one called invite.ics and the other called with the name of the subject of the invite. I am not sure if this the expected behavior.

**Comment by IT-AND-GENERAL** [comment] 2019-06-28 09:51
If I try to manually import the event by using one or the other .ics file I get:

1 events failed: The value "817bd34d-2c0e-5c22-9292-60d673e591b1" entered for the field "Uuid" already exists in the database. The field value must be unique. Please enter a different value in that field.


1 events failed: The value "817bd34d-2c0e-5c22-9292-60d673e591b1" entered for the field "Uuid" already exists in the database. The field value must be unique. Please enter a different value in that field.

**Comment by IT-AND-GENERAL** [comment] 2019-06-28 09:57
Other thing I noticed is that The event shows on my calendar but when I click on it I get:
The participant of this event is missing

**Comment by mschering** [comment] 2019-08-16 14:13
Could you send me exact steps to replicate this? I fail to replicate the problem.

**Comment by mschering** [comment] 2019-08-19 12:42
Please retest this in 6.4.41. I think I solved this.

**Comment by IT-AND-GENERAL** [comment] 2019-08-21 08:46
Yep, this seems ok now.

**Comment by IT-AND-GENERAL** [comment] 2019-08-28 17:06
This is still happening but only when the invite is sent via a mobile phone (Android 9)
See new Issue: 6.4.46 - Calendar - Error accepting invite from other GO user when sent from a mobile phone

**Comment by mschering** [comment] 2020-05-01 07:14
Closing this one as it's duplicate of #451

**Closed by mschering** 2020-05-01 07:14 UTC
