### ISSUE TITLE
update 6.3 -> 6.4

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#398] opened 2019-06-16 11:59 UTC
modules leavedays, documenttemplates, scanbox and savemailas gives missing license error on community edition so update stops working untill moduls are removed manually from file system.

Putting them back after update everthing works fine.

**Comment by mschering** [comment] 2019-06-18 13:11
On which version did you test this? I can't reproduce this. I'm getting this as expected:

<img width="756" alt="Screenshot 2019-06-18 at 15 10 23" src="https://user-images.githubusercontent.com/1314447/59684889-3f74df00-91db-11e9-8176-4204592388f0.png">
<img width="756" alt="Screenshot 2019-06-18 at 15 10 30" src="https://user-images.githubusercontent.com/1314447/59684890-3f74df00-91db-11e9-933a-af0e8dcdd7bf.png">

 with 6.4.21.

**Comment by remmedia** [comment] 2019-06-18 19:11
6.3.latest on Sunday to 6.4.21 (actuel release on sunday)

**Comment by mschering** [comment] 2019-06-20 15:20
I think I found the problem. This should be fixed in 6.4.23

**Closed by mschering** 2019-06-20 15:20 UTC
