### ISSUE TITLE
6.4.163 unknown recipient dialog

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#607] opened 2020-08-07 21:21 UTC
Hello,

since the last updates, two new bugs appeared:

1. The icons for adding the contact next to the unknown address are no longer visible unless you bring your mouse over them
2. Once you click to add the contact, it adds two empty e-mail address fields

**Comment by dehart** [comment] 2020-08-10 14:50
1. This is intended behaviour.
2. Fixed in the next release!

**Comment by flaviozluca** [comment] 2020-08-19 16:18
Dear friends,

Just a small notice. Since this changed a bit, you might want to change the text a little bit.

It informs "You just sent an e-mail to one or more recipients that are not in your addressbook. Click on a name if you want to add that person or close this window."

*** But actually you dont click on name. You have to roll mouse over person's name to reveal the + icon/sign and click on that...

Maybe easier to show the + sign and just inform in text "click on the plus sign next to the name you want to add..."

If not "roll mouse over person's name to reveal the plus sign and click on it to add..."

my 2 cents :)

Thanks

**Closed** 2020-08-27 08:32 UTC
