### ISSUE TITLE
Calendar editing twice bug

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#331] opened 2019-02-20 13:40 UTC
In 6.3.64 , calendar

Edit an event, save it, works great.
Try to re-edit the same event, you can't get to it because clicking the pencil icon throws an error - attached.

Pressing F5 for a refresh fixes the problem, but only for one edit. Further ones throw the same error
![capture]
![capture](https://user-images.githubusercontent.com/15035337/53095576-3b65d880-34eb-11e9-8ffd-d38b44e3c8f6.JPG)

**Comment by sirdemoncze** [comment] 2019-02-20 13:44
Duplicate of #328

**Closed** 2019-04-16 14:59 UTC
