### ISSUE TITLE
E-mail - move to spam do not switch detail panel to selected message

### ISSUE THREAD

**Issue by michalcharvat** [Intermesh/groupoffice#593] opened 2020-06-28 10:46 UTC
When you mark email message as spam, message is moved to spam folder and selected row in grid with messages switched to the next message. However the detail panel still display old message.

**Comment by thomasgg23** [comment] 2020-07-07 15:17
I think this is a duplicate of #589 is fixed in version 6.4.156, released a few minutes ago

**Closed** 2020-09-28 12:13 UTC
