### ISSUE TITLE
admin module overview - Element.alignToXY with an element that doesn't exist

### ISSUE THREAD

**Issue by wnglobal2000** [Intermesh/groupoffice#872] opened 2022-08-01 12:34 UTC
Dear Intermesh team,

we noticed this warning in debug mode. It's a low prio issue.

### Environment:
Version: 6.6.110
Apache: 2.4.41
MySQL: 8.0.29

cat /etc/groupoffice/config.php
$config['db_name'] = 'groupoffice';
$config['db_host'] = 'localhost';
$config['db_user'] = 'groupoffice';
$config['db_pass'] = '***************************';
$config['db_port'] = 3306;
$config['file_storage_path'] = '/var/lib/groupoffice';
$config['tmpdir'] = '/tmp/groupoffice';
$config['debug'] = true;

### Reproduce:
Plain GO 6.6.110 installation into empty MySQL DB.

Opening module overview, set view to full size, switch between "all/available/installed" modules:

> uncaught exception: Element.alignToXY with an element that doesn't exist

appears.

**Screenshot**:
![2022-08-01_14-24](https://user-images.githubusercontent.com/23655076/182147509-bff4014c-9ef2-4020-b0aa-49a31d79bd90.png)

**Comment by derjoachim** [comment] 2022-09-26 10:10
This appears to have been resolved in the meantime. At least, I am unable to reproduce this error using the reproducing steps against the current code base. Could you update please and corfirm? Thanks!

**Comment by wnglobal2000** [comment] 2022-10-03 14:23
Today I updated our Testing environment to **6.6.119** and received again:

> **Es ist ein Fehler aufgetreten.** 
> Weitere Details finden Sie in der Konsole.<br><br>uncaught exception: Element.alignToXY with an element that doesn't exist

Attached you will find the Log and Screenshot.
![872_20221003_Error_alignToXY](https://user-images.githubusercontent.com/23655076/193601344-6c1f7492-44e7-45d5-bd82-1319dd6f61aa.png)
[872_20221003_debug.log](https://github.com/Intermesh/groupoffice/files/9698281/872_20221003_debug.log)

**Comment by mschering** [comment] 2022-10-04 08:47
I found the issue. Fixed in 6.6.120.

**Closed** 2022-10-04 08:47 UTC
