### ISSUE TITLE
calendar current day

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#326] opened 2019-02-18 15:00 UTC
There seems to be an issue where the day shown on the small month calendar changes when you cycle through the months always showing that day but in a different month.

![calendar](https://user-images.githubusercontent.com/37214605/52959347-e2ccf900-338d-11e9-8bec-e148828e9a03.gif)

**Comment by michalcharvat** [comment] 2019-02-18 20:27
It is not a bug. It is framework feature - check latest examples https://examples.sencha.com/extjs/6.7.0/examples/kitchensink/?classic#calendar-panel (open event dialog). As you can see nothing change since ExtJS 3 :)

**Comment by Jonnybt4** [comment] 2019-02-19 15:09
So to confirm, the date this was submitted was the 18th on Feb which is highlighted in a blue circle and when I go to the next month it is supposed to hight the 18th of March, April, May etc, rather than disappear so that you don't think you have that day selected?

**Comment by michalcharvat** [comment] 2019-02-20 14:25
Correct. You can always create override for 
```
showNextMonth : function(e){
        this.update(this.activeDate.add('mo', 1));
},
```
to change default functionality. 

https://docs.sencha.com/extjs/3.4.0/#!/api/Date-method-add
https://docs.sencha.com/extjs/3.4.0/source/DatePicker.html#Ext-DatePicker

**Comment by mschering** [comment] 2019-04-16 14:59
Fixed in the next release

**Closed by mschering** 2019-04-16 14:59 UTC
