### ISSUE TITLE
GroupOffice 6.8.25 , does not show users list in Admin nor per user permissions window for assigning email access as read only

### ISSUE THREAD

**Issue by deependhulla** [Intermesh/groupoffice#1084] opened 2023-12-21 12:25 UTC
We recently upgraded from GroupOffice 6.7.60 to GroupOffice 6.8.25. with php 8.2 on Debian 11.8

We had assigned read-only access to a few user email-accounts.

Today, after the upgrade, we are unable to view the list of email users in the Admin login, nor can we grant email access permission as read-only on a per-user basis. As a now we created a temp group add both user into it to give read-only access based on group. 

To grant permissions, follow these steps:

Go to Email -> 3 Dots -> Accounts.
Select 'your-email-account.'
Navigate to 'Permissions.'
Click the '+' sign to add permissions.
However, it seems that only groups in which you are a member are displayed, and individual users are not visible. Previously, as a GroupOffice admin, you could directly manage anyone's properties, but now it appears to be disabled or not working. 

 Please provide guidance on how to resolve this issue.

**Comment by derjoachim** [comment] 2024-01-02 12:47
Is this issue still reproducible with 6.8.26? I am unable to reproduce this issue on my dev environment. That is: when I log in as a non-admin user and I want to manage permissions to a mailbox, I can see all users and groups, regardless of membership.

**Comment by deependhulla** [comment] 2024-01-03 05:12
same, have upgrade to to 6.8.26 ..and it still does not show user list only group for permissions to assign some one mail-box read access for example.

**Comment by mschering** [comment] 2024-01-04 15:23
It could be a permissions problem. It's possible you can't see the users:

See here for more info: https://groupoffice.readthedocs.io/en/latest/system-settings/users.html#visibility-of-users

**Comment by deependhulla** [comment] 2024-01-06 09:58
Thank you for the trick; it worked for configuring visibility on a per-user basis. However, I've noticed that when you recheck the user for permission in the UI, it disappears. Additionally, permissions from the group don't seem to be functioning correctly. I suspect this may be due to the recent upgrade. I will need to verify this by testing on a dummy setup with a fresh installation to confirm the issue.

**Comment by mschering** [comment] 2024-01-08 07:57
Yes, this bug will be fixed in the new release today.

**Comment by deependhulla** [comment] 2024-01-17 11:12
Upgraded to 6.8.29 , issue remains, But a Fresh linux PC with fresh setup of 6.8.29 works good.

**Closed** 2024-06-17 08:12 UTC

**Comment by deependhulla** [comment] 2024-06-17 11:50
With GroupOffice 6.8.54, for old user selection is an issue (not displayed), but not with new one created after 6.8.29 is visible.
